version: "3.9"
services:
  ingestion:
    build: data_ingestion
    ports:
      - "7270:7270"
  preprocessing:
    build: data_preprocessing
    ports:
      - "7271:7271"
  selection:
    build: model_selection
    ports:
      - "7272:7272"
    volumes:
      - model:/models
  training:
    build: model_training
    ports:
      - "7273:7273"
    volumes:
      - model:/models
  evaluation:
    build: model_evaluation
    ports:
      - "7274:7274"
    volumes:
      - model:/models
volumes:
  model: